[package]
name = "async_article_code_1"
version = "0.1.0"
authors = ["Moazzam Adil Khan <moaadi3890@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.4"
async-std = "1.5.0"